### Dynamic Programming

With help of a value grid we calculate the costs to the goal from every possible position so we can instantly decide in every situation which way or alternative way to go.

In [16]:
# ----------
# User Instructions:
# 
# Create a function compute_value which returns
# a grid of values. The value of a cell is the minimum
# number of moves required to get from the cell to the goal. 
#
# If a cell is a wall or it is impossible to reach the goal from a cell,
# assign that cell a value of 99.
# ----------

import numpy as np

grid = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]


grid2 = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]

goal = [len(grid)-1, len(grid[0])-1]
cost = 1 # the cost associated with moving from a cell to an adjacent one

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['^', '<', 'v', '>']

def compute_value_and_policy(grid,goal,cost):
    # ----------------------------------------
    # insert code below
    # ----------------------------------------
    
    optimized = True
    
    width = len(grid[0])
    height = len(grid)
    
    value = [[99 for j in range(width)] for i in range(height)];
    policy = [[' ' for j in range(width)] for i in range(height)];
    value[goal[0]][goal[1]] = 0
    policy[goal[0]][goal[1]] = '*'
    
    while optimized:
        optimized = False
        for y in range(height):
            for x in range(width):
                base_costs = value[y][x]
                for di in range(len(delta)):
                    dt = delta[di]                    
                    y2 = y+dt[0]
                    x2 = x+dt[1]
                    if x2<0 or y2<0 or x2>=width or y2>=height:
                        continue
                    if grid[y2][x2]==1:
                        continue
                    if value[y2][x2]>base_costs+cost:
                        value[y2][x2] = base_costs+cost
                        policy[y2][x2] = delta_name[(di+2)%4]
                        optimized = True                    
    
    # make sure your function returns a grid of values as 
    # demonstrated in the previous video.
    return value, policy

def compute_value(grid,goal,cost):
    value, policy = compute_value_and_policy(grid,goal,cost)
    return value

def optimum_policy(grid,goal,cost):
    value, policy = compute_value_and_policy(grid,goal,cost)
    return policy
    
print(np.array(compute_value(grid,goal,cost)))
print(np.array(optimum_policy(grid2,goal,cost)))

[[11 99  7  6  5  4]
 [10 99  6  5  4  3]
 [ 9 99  5  4  3  2]
 [ 8 99  4  3  2  1]
 [ 7  6  5  4 99  0]]
[['v' ' ' '>' '>' '>' 'v']
 ['v' ' ' '>' '>' '>' 'v']
 ['v' ' ' '>' '>' '>' 'v']
 ['v' ' ' '>' '>' '>' 'v']
 ['>' '>' '>' '^' ' ' '*']]
